### ISSUE TITLE
Shiny.semantic inputs slow down the app

### ISSUE THREAD

**Issue by krystian8207** [Appsilon/shiny.semantic#144] opened 2019-11-26 12:23 UTC
Compare dropdown with selectInput and numericInput with shiny_text_input.

**Comment by ashbaldry** [comment] 2020-02-02 22:35
I've noticed when adding in the new inputs, the `delay` option for the `getRatePolicy` in the JS files seems to be the cause for this.

**Comment by dokato** [comment] 2020-03-13 10:34
Due to moving inputs logic into JS binding it may be fixed now, but still requires testing...

**Comment by krystian8207** [comment] 2020-07-03 15:22
@dokato We can close it. I verified the current package state and the performance is the same as for shiny components. The reason for that was the usage of `shiny_text_input` inside that has incorrectly precised ratePolicy based on the case (as @ashbaldry mentioned). As we tend now to use our custom bindings (without `shiny_text_input`) we can claim the issue is solved.

**Comment by dokato** [comment] 2020-07-03 15:31
great!

**Closed** 2020-07-03 15:32 UTC
Labels: enhancement
